### ISSUE TITLE
First container build won't create node_modules directory

### ISSUE THREAD

**Issue by thsfranca** [NeoAssist/NeoAcademy#9]
## Expected Behavior

Node modules directory should be created if do not exists

## Current Behavior

The first build of the frontend won't create the node_modules directory

## Possible Solution

Add `npm install` as a command to run the container

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by r0x0d** [comment]
close #9
